#!/bin/sh

# First remove any leading, trailing, or multiple colons
PATH="$( printf "%s" "$PATH" | sed 's/^:\+//;s/:\+$//;s/:\+/:/;' )"

# Remove all subsequent duplicate entries from the path, leaving only the first
# of each entry in the intended order
PATH="$( printf "%s" "$PATH" | awk 'BEGIN{ORS=":";RS=":"}$0&&!a[$0]++' )"

# Remove the trailing record separator character left behind by awk
PATH="${PATH%:}"

export PATH
